### PR TITLE
Add more exterior pics

### PR DESCRIPTION
**Pull request by bictorv**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Would it be possible to add a closeup of the LMI label?  Also other details, if any.

**Comment by ams** [comment]
I have it in vector graphics.

**Comment by larsbrinkhoff** [comment]
I could well see this on a t-shirt:
```
 C H A O S
  NETWORK
TRANSCIEVER
```

**Comment by bictorv** [comment]
@ams would you care to share? And yes for a t-shirt! :-)

**Comment by ams** [comment]
[lmi-svg.zip](https://github.com/Chaosnet/pictures/files/13467010/lmi-svg.zip)

**Comment by larsbrinkhoff** [comment]
Thanks!  Merging.

**Pull request merged**
