### PR TITLE
Pics from Update

### PR DESCRIPTION
**Pull request by bictorv**
Some more exterior pictures are coming soon.

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Very interesting!  It looks like schematics could be recreated from this, if necessary.  And the existing SUDS drawings can be checked against the real thing.  CC @kahrs

**Comment by ams** [comment]
Where are the SUDS for the transceiver?

**Comment by kahrs** [comment]
Attached.

**Comment by ams** [comment]
Seems something ate the attachment?

**Comment by larsbrinkhoff** [comment]
https://github.com/Chaosnet/suds-drawings

**Comment by ams** [comment]
Those drawings are for the Chaosnet board for the Lisp Machine, not for the transceiver.

**Comment by kahrs** [comment]
Don't be so sure.  I think those schematics are actually 3 in 1: Lisp machine, Q / Uni bus and the transceiver.

I am attaching the transceiver schematics as I extracted them.  It's quite different from the photo, it's mainly a VMOS power FET.  Note the use of an HP opto-isolator instead of a transformer.

[transceiver.pdf](https://github.com/Chaosnet/pictures/files/13442895/transceiver.pdf)

**Comment by ams** [comment]
Missed the ARC directory.  Thanks!

**Pull request merged**
